# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sp_ui_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from sp_ui_result import Result_Ui_MainWindow


class Data_Ui_MainWindow(object):
    def __init__(self, result_schedule):
        self.result_schedule = result_schedule
        self.cashWindow = QtWidgets.QMainWindow()
        self.cashwin = Result_Ui_MainWindow()
        self.cashwin.setupUi(self.cashWindow, schedule=self.result_schedule)

    def setupUi(self, MainWindow, depts, mts, rooms, instructors, courses):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)

        # Meeting Times
        self.mt_table = QtWidgets.QTableWidget(self.centralwidget)
        self.mt_table.setObjectName("mt_table")
        self.mt_table.setColumnCount(2)
        self.mt_table.setRowCount(len(mts))
        # Set data for mts
        for i in range(len(mts)):
            # meeting_times[i].get_id(), meeting_times[i].get_time()
            self.mt_table.setItem(
                i, 0, QtWidgets.QTableWidgetItem(mts[i].get_id()))
            self.mt_table.setItem(
                i, 1, QtWidgets.QTableWidgetItem(str(mts[i].get_time())))
        for i in range(len(mts)):
            self.mt_table.resizeColumnToContents(i)

        item = QtWidgets.QTableWidgetItem()
        self.mt_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mt_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_5.addWidget(self.mt_table)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        # Rooms
        self.room_table = QtWidgets.QTableWidget(self.centralwidget)
        self.room_table.setObjectName("room_table")
        self.room_table.setColumnCount(2)
        self.room_table.setRowCount(len(rooms))
        # Set data for rooms
        for i in range(len(rooms)):
            self.room_table.setItem(
                i, 0, QtWidgets.QTableWidgetItem(rooms[i].get_number()))
            self.room_table.setItem(
                i, 1, QtWidgets.QTableWidgetItem(str(rooms[i].get_seating_capacity())))
        for i in range(len(rooms)):
            self.room_table.resizeColumnToContents(i)

        item = QtWidgets.QTableWidgetItem()
        self.room_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.room_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.room_table)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        # Instructors
        self.instructor_table = QtWidgets.QTableWidget(self.centralwidget)
        self.instructor_table.setObjectName("instructor_table")
        self.instructor_table.setColumnCount(2)
        self.instructor_table.setRowCount(len(instructors))
        # Set data for courses
        for i in range(len(instructors)):
            self.instructor_table.setItem(
                i, 0, QtWidgets.QTableWidgetItem(instructors[i].get_id()))
            self.instructor_table.setItem(
                i, 1, QtWidgets.QTableWidgetItem(instructors[i].get_name()))
        for i in range(len(courses)):
            self.instructor_table.resizeColumnToContents(i)

        item = QtWidgets.QTableWidgetItem()
        self.instructor_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.instructor_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.instructor_table)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        # Courses
        self.course_table = QtWidgets.QTableWidget(self.centralwidget)
        self.course_table.setObjectName("course_table")
        self.course_table.setColumnCount(4)
        self.course_table.setRowCount(len(courses))
        # Set data for courses
        for i in range(len(courses)):
            instructors = courses[i].get_instructors()
            temp_str = ''
            for j in range(len(instructors) - 1):
                temp_str += instructors[j].__str__() + ', '
            temp_str += instructors[len(instructors) - 1].__str__()
            self.course_table.setItem(
                i, 0, QtWidgets.QTableWidgetItem(courses[i].get_number()))
            self.course_table.setItem(
                i, 1, QtWidgets.QTableWidgetItem(courses[i].get_name()))
            self.course_table.setItem(
                i, 2, QtWidgets.QTableWidgetItem(str(courses[i].get_max_num_of_students())))
            self.course_table.setItem(
                i, 3, QtWidgets.QTableWidgetItem(temp_str))
        for i in range(len(courses)):
            self.course_table.resizeColumnToContents(i)

        item = QtWidgets.QTableWidgetItem()
        self.course_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.course_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.course_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.course_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.course_table)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        # Departments
        self.dept_table = QtWidgets.QTableWidget(self.centralwidget)
        self.dept_table.setObjectName("dept_table")
        self.dept_table.setColumnCount(2)
        self.dept_table.setRowCount(len(depts))
        # Set data in the table
        for i in range(len(depts)):
            courses = depts[i].get_courses()
            temp_str = '['
            for j in range(len(courses) - 1):
                temp_str += courses[j].__str__() + ','
            temp_str += courses[len(courses) - 1].__str__() + ']'
            self.dept_table.setItem(
                i, 0, QtWidgets.QTableWidgetItem(depts[i].get_name()))
            self.dept_table.setItem(
                i, 1, QtWidgets.QTableWidgetItem(temp_str))
        self.dept_table.resizeColumnToContents(0)
        self.dept_table.resizeColumnToContents(1)
        self.course_table.resizeRowsToContents()

        item = QtWidgets.QTableWidgetItem()
        self.dept_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dept_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.dept_table)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.create_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_button.setObjectName("create_button")
        self.horizontalLayout_6.addWidget(self.create_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)

        self.create_button.clicked.connect(self.openWindow)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 743, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def openWindow(self):
        self.cashWindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Available Data"))
        self.label_5.setText(_translate("MainWindow", "Meeting Times"))
        item = self.mt_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.mt_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Meeting Time"))
        self.label_2.setText(_translate("MainWindow", "Rooms"))
        item = self.room_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Room"))
        item = self.room_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MSC"))
        self.label_3.setText(_translate("MainWindow", "Instructors"))
        item = self.instructor_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.instructor_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Instructor"))
        self.label_4.setText(_translate("MainWindow", "Courses"))
        item = self.course_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.course_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Course"))
        item = self.course_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MoS"))
        item = self.course_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Instructor"))
        self.label.setText(_translate("MainWindow", "Departments and Courses"))
        item = self.dept_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Department"))
        item = self.dept_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Courses"))
        self.create_button.setText(_translate("MainWindow", "Create Schedule"))
